<div class="article">
        <h1 class="title">Article Title</h1>
        <div class="section1 article-section">
            <div class="articles-content">
                <div class="article ">
                    
                    <img src="<?= $_SESSION["article"]['image'] ?>" alt="image article">
                    <p class="title-article"><?= $_SESSION["article"]['title'] ?></p>
                    <p class="short-description"><?= $_SESSION["article"]['content'] ?></p>
                    <p >publié le: <span class="date"><?= $_SESSION["article"]['created_at'] ?></span> </p>
                    <p>Autheur: <span class="author">Joey Star</span> </p>
                </div>     
            </div>
           
        </div>
</div>