<h3 class="title">Gestion des articles</h3>
<div class="articles">
    <div class="container-form">
        <form action="" method="POST" class="form-article">
            <h4>Créer un article</h4>
            <div>
                <label for="title">Titre</label>
                <input type="text" name="tite">
            </div>
            <div>
                <label for="image">Lien vers l'image</label>
                <input type="text" name="image">
            </div>
            <div>
                <label for="content">Contenu</label>
                <textarea name="content" cols="30" rows="10"></textarea>
            </div>
            <input type="submit" value="Valider">
        </form>
    </div>
    <div class="user">
    <h4 class="title"> Gérér un article</h4>
       <ul>
           <li><span class="title">Peugeot une marque qui se réinvente</span>  <a href="/Blog/dashboard/article/id" class="icon"><i class="fas fa-trash-alt"></i></a></li>
           <li><span class="name">Forza Motors de plus en plus performant</span> <a href="/Blog/dashboard/article/id" class="icon"><i class="fas fa-trash-alt"></i></a></li>
    
       </ul>
    </div>
</div>