<h3 class="title">Gestion des articles</h3>
<div class="articles">
    <div class="container-form">
        <form action="/Blog/dashboard/articles" method="POST" class="form-article">
            <h4>Créer un article</h4>
            <div>
                <label for="title">Titre</label>
                <input type="text" name="title">
            </div>
            <div>
                <label for="image">Lien vers l'image</label>
                <input type="text" name="image">
            </div>
            <div>
                <label for="content">Contenu</label>
                <textarea name="content" cols="30" rows="10"></textarea>
            </div>
            <input type="submit" value="Valider">
        </form>
    </div>
    <div class="user">
    <h4 class="title"> Gérér un article</h4>
    
       <ul>
           <?php foreach($_SESSION["articles"] as $article): ?>
           <li><span class="name"><?= $article['title'] ?></span>  <a href="/Blog/dashboard/articles/<?= $article['id_article'] ?>" class="icon"><i class="fas fa-trash-alt"></i></a></li>
            <?php endforeach; ?>
       </ul>
    </div>
</div>