<header>
    <div class="wholeHeader">
        <!-- Partie gauche du header -->
        <div class="leftSideHeader">
            <img src="../../public/img/LogoBlog.jpg" alt="Logo Blog" class="imgLogo">
            <strong class="brigade">Brigade des fans de voiture</strong>
        </div>

        <?php if (isset($_SESSION["firstname"])): ?>
            <div class="rightSideHeader">
                <!-- <img src="Image utilisateur quand connecté" alt="Your User Image"> -->
                <p class="greetUser">Bonjour, David !</p>  
                <ul class="menuUser">
                    <li class="deroulant">
                        <i class="fas fa-arrow-right arrow" id="arrow"> Menu</i>
                        <ul class="sous">
                            <li><a href="./logout" class="logout">Déconnection</a></li>
                            <li><a href="./settings" class="settings">Paramètres</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        <?php else: ?>
            <div class="rightSideHeader ">
                <!-- <img src="Image utilisateur quand connecté" alt="Your User Image"> -->
                <p class="greetUser">Bonjour, David !</p>  
                <ul class="menuUser">
                    <li class="deroulant">
                        <i class="fas fa-arrow-right arrow" id="arrow"> Menu</i>
                        <ul class="sous">
                            <li><a href="./logout" class="logout">Déconnection</a></li>
                            <li><a href="./settings" class="settings">Paramètres</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        <?php endif; ?>

    </div>
    <nav>
        <ul>
            <li><a href="./home">Home</a></li>
            <li><a href="./register">S'inscrire</a></li>
            <li><a href="./login">Se connecter</a></li>
        </ul>
    </nav>
</header>