<header>
    <div class="wholeHeader">
        <!-- Partie gauche du header -->
        <div class="leftSideHeader">
            <img src="../../public/img/LogoBlog.jpg" alt="Logo Blog" class="imgLogo">
            <strong class="brigade">Brigade des fans de voiture</strong>
        </div>

        <div class="rightSideHeader">
            <!-- <img src="Image utilisateur quand connecté" alt="Your User Image"> -->
            <p class="greetUser">Bonjour, David !</p>  
            <ul class="menuUser">
                <li class="deroulant">
                    <i class="fas fa-arrow-right arrow" id="arrow"> Menu</i>
                    <ul class="sous">
                        <li><a href="./logout" class="logout">Déconnection</a></li>
                        <li><a href="./settings" class="settings">Paramètres</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <nav>
            <ul>
                <li><a href="./blog"></a></li>
                <li><a href="./login"></a></li>
                <li><a href="./register"></a></li>
            </ul>
        </nav>

    </div>
</header>