<header>
    <div class="wholeHeader">
        <!-- Partie gauche du header -->
        <div class="leftSideHeader">
        <a href="./home"><img src="../../public/img/LogoBlog.jpg" alt="Logo Blog" class="imgLogo"></a>
            <strong class="brigade">Brigade des fans de voiture</strong>
        </div>

        <?php if (isset($_SESSION["firstname"])): ?>
            <div class="rightSideHeader">
                <!-- <img src="Image utilisateur quand connecté" alt="Your User Image"> -->
                <p class="greetUser">Bonjour, David !</p>  
                <ul class="menuUser">
                    <li class="deroulant">
                        <i class="fas fa-arrow-right arrow" id="arrow"> Menu</i>
                        <ul class="sous">
                            <li><a href="/Blog/logout" class="logout">Déconnection</a></li>
                            <li><a href="/Blog/settings" class="settings">Paramètres</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        <?php else: ?>
            <div class="rightSideHeader hidden">
                <p class="greetUser">Bonjour, David !</p>  
                <ul class="menuUser">
                    <li class="deroulant">
                        <i class="fas fa-arrow-right arrow" id="arrow"> Menu</i>
                        <ul class="sous">
                            <li><a href="/Blog/logout" class="logout">Déconnection</a></li>
                            <li><a href="/Blog/settings" class="settings">Paramètres</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        <?php endif; ?>

    </div>
    <nav>
        <ul>
            <li><a href="/Blog/home">Home</a></li>
            <?php if($_SESSION['connected'] == false): ?>
                <li><a href="/Blog/register">S'inscrire</a></li>
                <li><a href="/Blog/login">Se connecter</a></li>
            <?php else: ?>
            <li><a href="/Blog/dashboard">dashboard</a></li>
            <li><a href="/Blog/logout">Déconnection</a></li>
            <?php endif; ?>
        </ul>
    </nav>
</header>