<div class="home">
        <h1 class="title">Accueil</h1>
        <div class="section1">
            <h2 class="title">Nos derniers articles</h2>
            <ul class="articles-content">
                
                    <li class="article">
                        <img src="https://images.caradisiac.com/images/5/6/2/3/95623/S1-Voici-la-Peugeot-208-GTI-30th-au-comportement-aiguise-325245.jpg" alt="image article">
                        <p class="title-article">Peugeot Une marque qui ne cesse de se réiventer</p>
                        <p class="short-description">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum, blanditiis commodi distinctio sed saepe qui adipisci maxime, in asperiores debitis quae esse neque quidem eos ab dolorem, earum quibusdam facere?</p>
                        <div class="button-container">
                            <a href="./article/id"> voir plus</a>
                        </div>
                    </li>
                    <li class="article">
                        <img src="https://images4.alphacoders.com/104/thumb-1920-1046176.jpg" alt="image article">
                        <p class="title-article">Peugeot Une marque qui ne cesse de se réiventer</p>
                        <p class="short-description">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum, blanditiis commodi distinctio sed saepe qui adipisci maxime, in asperiores debitis quae esse neque quidem eos ab dolorem, earum quibusdam facere?</p>
                        <div class="button-container">
                            <a href="./article/id"> voir plus</a>
                        </div>
                    </li>
                   
            </ul>
        </div>
</div>