<div class="home">
        <h1 class="title">Accueil</h1>
        <div class="section1">
            <h2 class="title">Nos derniers articles</h2>
            <ul class="articles-content">
                <?php foreach($_SESSION["articles"] as $article): ?>
                    <li class="article">
                        <img src="<?= $article['image'] ?>" alt="image article">
                        <p class="title-article"><?= $article['title'] ?></p>
                        <p class="short-description"><?= $article['content'] ?></p>
                        <div class="button-container">
                            <a href="./article/<?= $article['id_article'] ?>"> voir plus</a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
</div>