<h3 class="title">Gestion du profile</h3>
<div class="container-form">
    <form action="" method="POST" class="profile">
        <div>
            <label for="firstname">Prénom</label>
            <input type="text">
        </div>
        <div>
            <label for="lastname">Nom</label>
            <input type="text">
        </div>
        <div>
            <label for="email">E-mail</label>
            <input type="email">
        </div>
        <div>
            <label for="password">password</label>
            <input type="password">
        </div>
        <input type="submit" value="Valider">
    </form>
</div>