<div class="container-login100">
    <div class="wrap-login100">
        <form class="login100-form validate-form" action="/Blog/register" method="POST">
            <span class="login100-form-title p-b-26">
                Welcome
            </span>
            <div class="wrap-input100 validate-input">
                <input class="input100" type="text" name="firstname" placeholder="Prénom">
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input">
                <input class="input100" type="text" name="lastname" placeholder="Nom de famille">
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input">
                <input class="input100" type="text" name="email" placeholder="Email">
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input">
                <input class="input100" type="password" name="password" placeholder="Password">
                <span class="focus-input100"></span>
            </div>
            <div class="container-login100-form-btn">
                <div class="wrap-login100-form-btn">
                    <div class="login100-form-bgbtn"></div>
                    <button class="login100-form-btn">
                        Valider
                    </button>
                </div>
            </div>
            <div class="text-center p-t-115">
                <span class="txt1">
                    Vous n'avez pas de compte ?
                </span>
                <a class="txt2" href="Blog/register">
                    Inscrivez-vous
                </a>
            </div>
        </form>
    </div>
</div>