<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $data["view"] ?></title>
</head>
<body>
    <!-- HEADER -->
    <?php require_once VIEW_DIR."/components/header.phtml"; ?>
    <!-- MAIN -->
    <main>
        <?php require_once VIEW_DIR."/components/".$data["view"].".phtml"; ?>
    </main>
    <!-- FOOTER -->
    <?php require_once VIEW_DIR."/components/footer.phtml"; ?>
</body>
</html>
