<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
    <link rel="stylesheet" href="public/scss/style.css">
    <title><?= $data["view"] ?></title>
</head>
<body>
    <!-- HEADER -->
    <?php require_once VIEW_DIR."/components/header.phtml"; ?>
    <!-- MAIN -->
    <main>
        <?php require_once VIEW_DIR."/components/".$data["view"].".phtml"; ?>
    </main>
    <!-- FOOTER -->
    <?php require_once VIEW_DIR."/components/footer.phtml"; ?>
</body>
<script type="text/javascript" src="public/js/main.js"></script>
</html>
